# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"my_print": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://Jaume-JCI.github.io/trial/"

git_url = "https://github.com/Jaume-JCI/trial/tree/main/"

def custom_doc_links(name): return None
