name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.6'
        architecture: 'x64'
    - name: Build the image
      run: |
        docker build -t dt . --build-arg TEST=1
    - name: Run tests in image
      run: |
        docker run --name dc dt
